# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FitView(object):
    def setupUi(self, FitView):
        FitView.setObjectName("FitView")
        FitView.resize(1150, 669)
        self.centralwidget = QtWidgets.QWidget(FitView)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.metadataFrame = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataFrame.sizePolicy().hasHeightForWidth())
        self.metadataFrame.setSizePolicy(sizePolicy)
        self.metadataFrame.setMinimumSize(QtCore.QSize(250, 250))
        self.metadataFrame.setObjectName("metadataFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.metadataFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.metadataStackedWidget = QtWidgets.QStackedWidget(self.metadataFrame)
        self.metadataStackedWidget.setObjectName("metadataStackedWidget")
        self.metadataStackedWidgetPage1 = QtWidgets.QWidget()
        self.metadataStackedWidgetPage1.setObjectName("metadataStackedWidgetPage1")
        self.metadataStackedWidget.addWidget(self.metadataStackedWidgetPage1)
        self.verticalLayout_3.addWidget(self.metadataStackedWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.metadataFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.graph = QtWidgets.QWidget(self.splitter)
        self.graph.setMinimumSize(QtCore.QSize(800, 0))
        self.graph.setObjectName("graph")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.splitter_2)
        self.stackedWidget_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.table_page = QtWidgets.QWidget()
        self.table_page.setObjectName("table_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.table_page)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.all_events_table = QtWidgets.QTableWidget(self.table_page)
        self.all_events_table.setObjectName("all_events_table")
        self.all_events_table.setColumnCount(5)
        self.all_events_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.all_events_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_events_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_events_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_events_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_events_table.setHorizontalHeaderItem(4, item)
        self.all_events_table.horizontalHeader().setDefaultSectionSize(200)
        self.all_events_table.verticalHeader().setDefaultSectionSize(25)
        self.all_events_table.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_2.addWidget(self.all_events_table)
        self.stackedWidget_3.addWidget(self.table_page)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.stackedWidget_3.addWidget(self.page_10)
        self.verticalLayout.addWidget(self.splitter_2)
        FitView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FitView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Import = QtWidgets.QMenu(self.menubar)
        self.menu_Import.setObjectName("menu_Import")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        FitView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FitView)
        self.statusbar.setObjectName("statusbar")
        FitView.setStatusBar(self.statusbar)
        self.action_Open_Logbook = QtWidgets.QAction(FitView)
        self.action_Open_Logbook.setObjectName("action_Open_Logbook")
        self.action_Import_Files = QtWidgets.QAction(FitView)
        self.action_Import_Files.setObjectName("action_Import_Files")
        self.action_Import_Device = QtWidgets.QAction(FitView)
        self.action_Import_Device.setObjectName("action_Import_Device")
        self.action_Exit = QtWidgets.QAction(FitView)
        self.action_Exit.setObjectName("action_Exit")
        self.action_New_Logbook = QtWidgets.QAction(FitView)
        self.action_New_Logbook.setObjectName("action_New_Logbook")
        self.action_Select = QtWidgets.QAction(FitView)
        self.action_Select.setObjectName("action_Select")
        self.action_Close_Logbook = QtWidgets.QAction(FitView)
        self.action_Close_Logbook.setObjectName("action_Close_Logbook")
        self.menu_File.addAction(self.action_New_Logbook)
        self.menu_File.addAction(self.action_Open_Logbook)
        self.menu_File.addAction(self.action_Close_Logbook)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Import.addAction(self.action_Import_Files)
        self.menuActions.addAction(self.action_Select)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Import.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(FitView)
        QtCore.QMetaObject.connectSlotsByName(FitView)

    def retranslateUi(self, FitView):
        _translate = QtCore.QCoreApplication.translate
        FitView.setWindowTitle(_translate("FitView", "MainWindow"))
        self.pushButton.setText(_translate("FitView", "Edit"))
        self.pushButton_2.setText(_translate("FitView", "Delete"))
        item = self.all_events_table.horizontalHeaderItem(0)
        item.setText(_translate("FitView", "Event Date"))
        item = self.all_events_table.horizontalHeaderItem(1)
        item.setText(_translate("FitView", "Event Name"))
        item = self.all_events_table.horizontalHeaderItem(2)
        item.setText(_translate("FitView", "Event Type"))
        item = self.all_events_table.horizontalHeaderItem(3)
        item.setText(_translate("FitView", "Event Subtype"))
        item = self.all_events_table.horizontalHeaderItem(4)
        item.setText(_translate("FitView", "RowId"))
        self.menu_File.setTitle(_translate("FitView", "&File"))
        self.menu_Import.setTitle(_translate("FitView", "&Import"))
        self.menuActions.setTitle(_translate("FitView", "Actions"))
        self.action_Open_Logbook.setText(_translate("FitView", "&Open Logbook"))
        self.action_Import_Files.setText(_translate("FitView", "Import Files"))
        self.action_Import_Device.setText(_translate("FitView", "Import Device"))
        self.action_Exit.setText(_translate("FitView", "&Exit"))
        self.action_New_Logbook.setText(_translate("FitView", "&New Logbook"))
        self.action_Select.setText(_translate("FitView", "Select"))
        self.action_Close_Logbook.setText(_translate("FitView", "&Close Logbook"))

